#!/usr/bin/env python3
"""Update SKILLS.md from ~/.codex/skills contents."""
from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_FILE = REPO_ROOT / "SKILLS.md"

CODEX_HOME = Path.home() / ".codex" / "skills"
DIST_DIR = CODEX_HOME / "dist"


def find_skill_dirs(base: Path) -> list[Path]:
    if not base.exists():
        return []
    skills = []
    for entry in sorted(base.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name.startswith("."):
            continue
        if entry.name == "dist":
            continue
        if (entry / "SKILL.md").exists():
            skills.append(entry)
    return skills


def render_index(skill_dirs: list[Path]) -> str:
    lines = [
        "# Skills Index",
        "",
        "This repo uses local Codex skills stored under `~/.codex/skills`.",
        "",
        "Generated by `scripts/update-skills-index.py`.",
        "",
        "## Installed skills",
    ]
    if not skill_dirs:
        lines.append("- (none found)")
        lines.append("")
        return "\n".join(lines)

    for skill_dir in skill_dirs:
        name = skill_dir.name
        package = DIST_DIR / f"{name}.skill"
        lines.append(f"- {name}")
        lines.append(f"  - Folder: `{skill_dir}`")
        if package.exists():
            lines.append(f"  - Package: `{package}`")
        else:
            lines.append("  - Package: (not packaged)")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    skill_dirs = find_skill_dirs(CODEX_HOME)
    content = render_index(skill_dirs)
    SKILLS_FILE.write_text(content)


if __name__ == "__main__":
    main()
