-- Supabase schema for HAVI (BIGINT PKs)
-- Assumes a fresh schema. If tables already exist with UUID PKs, drop/recreate before running.

create extension if not exists "vector";

-- Core identity mapping (optional, keeps API int user_id fields stable)
create table if not exists app_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists families (
  id bigint generated by default as identity primary key,
  name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists family_members (
  family_id bigint not null references families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  is_primary boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (family_id, user_id)
);
create index if not exists family_members_user_id_idx on family_members(user_id);
create index if not exists family_members_family_id_idx on family_members(family_id);

create table if not exists caregiver_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  email text,
  phone text,
  relationship text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists children (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  name text,
  first_name text,
  last_name text,
  birth_date date,
  due_date date,
  gender text,
  birth_weight numeric,
  birth_weight_unit text,
  latest_weight numeric,
  latest_weight_date date,
  timezone text default 'UTC',
  routine_eligible boolean default false,
  adjusted_birth_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint children_birth_or_due_check check (birth_date is not null or due_date is not null),
  constraint children_gender_check check (gender in ('boy','girl','unknown') or gender is null)
);
create index if not exists children_family_id_idx on children(family_id);

create table if not exists memory_chunks (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  child_id bigint null references children(id) on delete cascade,
  source_type text not null,
  source_id text not null,
  content text not null,
  embedding vector(1536),
  created_at timestamptz default now()
);
create index if not exists memory_chunks_family_id_idx on memory_chunks(family_id);

create table if not exists conversation_sessions (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  child_id bigint null references children(id) on delete set null,
  user_id bigint null references app_users(id),
  title text not null default 'New chat',
  is_active boolean default true,
  last_message_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  catch_up_mode boolean default false,
  catch_up_started_at timestamptz,
  catch_up_last_message_at timestamptz
);
create index if not exists conversation_sessions_family_id_idx on conversation_sessions(family_id);
create index if not exists conversation_sessions_child_id_idx on conversation_sessions(child_id);

create table if not exists conversation_messages (
  id bigint generated by default as identity primary key,
  session_id bigint not null references conversation_sessions(id) on delete cascade,
  user_id bigint null references app_users(id),
  role text not null,
  content text not null,
  intent text,
  created_at timestamptz default now()
);
create index if not exists conversation_messages_session_id_idx on conversation_messages(session_id);

create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  child_id bigint not null references children(id) on delete cascade,
  user_id bigint null references app_users(id),
  actions_json jsonb not null,
  source text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists activity_logs_family_id_idx on activity_logs(family_id);
create index if not exists activity_logs_child_id_idx on activity_logs(child_id);

create table if not exists timeline_events (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  child_id bigint not null references children(id) on delete cascade,
  type text not null,
  title text not null,
  detail text,
  amount_label text,
  start timestamptz not null,
  "end" timestamptz,
  has_note boolean default false,
  is_custom boolean default false,
  source text,
  origin_message_id bigint,
  created_at timestamptz default now()
);
create index if not exists timeline_events_family_id_idx on timeline_events(family_id);
create index if not exists timeline_events_child_start_idx on timeline_events(child_id, start);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  child_id bigint null references children(id) on delete set null,
  title text not null,
  status text not null default 'open',
  due_at timestamptz,
  remind_at timestamptz,
  completed_at timestamptz,
  reminder_channel text,
  last_reminded_at timestamptz,
  snooze_count integer default 0,
  is_recurring boolean default false,
  recurrence_rule text,
  created_at timestamptz default now(),
  created_by_user_id bigint null references app_users(id),
  assigned_to_user_id bigint null references app_users(id)
);
create index if not exists tasks_family_id_idx on tasks(family_id);
create index if not exists tasks_child_id_idx on tasks(child_id);
create index if not exists tasks_status_idx on tasks(status);

create table if not exists routine_metrics (
  id bigint generated by default as identity primary key,
  child_id bigint not null unique references children(id) on delete cascade,
  prompt_shown_count integer default 0,
  accepted_count integer default 0,
  first_prompt_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists daily_child_metrics (
  id bigint generated by default as identity primary key,
  child_id bigint not null references children(id) on delete cascade,
  date date not null,
  metrics_json jsonb not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(child_id, date)
);

create table if not exists knowledge_items (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  profile_id bigint not null references app_users(id),
  key text not null,
  type text not null,
  status text not null,
  payload jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  last_prompted_at timestamptz,
  last_prompted_session_id bigint
);
create index if not exists knowledge_items_family_id_idx on knowledge_items(family_id);
create index if not exists knowledge_items_profile_id_idx on knowledge_items(profile_id);
create index if not exists knowledge_items_status_idx on knowledge_items(status);

create table if not exists inferences (
  id bigint generated by default as identity primary key,
  family_id bigint not null references families(id) on delete cascade,
  child_id bigint null references children(id) on delete set null,
  user_id bigint null references app_users(id),
  inference_type text not null,
  payload jsonb not null default '{}',
  confidence numeric default 0.5,
  status text not null default 'pending',
  source text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  expires_at timestamptz,
  dedupe_key text,
  last_prompted_at timestamptz
);
create unique index if not exists inferences_dedupe_key_idx on inferences(dedupe_key);
create index if not exists inferences_family_id_idx on inferences(family_id);

create table if not exists message_feedback (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references conversation_sessions(id) on delete cascade,
  message_id bigint not null references conversation_messages(id) on delete cascade,
  user_id bigint null references app_users(id),
  session_id text,
  rating text not null check (rating in ('up','down')),
  feedback_text text,
  model_version text,
  response_metadata jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create unique index if not exists message_feedback_user_unique
  on message_feedback(conversation_id, message_id, user_id)
  where user_id is not null;
create unique index if not exists message_feedback_session_unique
  on message_feedback(conversation_id, message_id, session_id)
  where session_id is not null;

create table if not exists share_links (
  token text primary key,
  session_id bigint not null references conversation_sessions(id) on delete cascade,
  created_at timestamptz default now(),
  expires_at timestamptz
);

create table if not exists loading_metrics (
  id bigint generated by default as identity primary key,
  session_id bigint null references conversation_sessions(id) on delete set null,
  message_id bigint null references conversation_messages(id) on delete set null,
  thinking_short_ms double precision,
  thinking_rich_ms double precision,
  error_type text,
  retry_count integer,
  created_at timestamptz default now()
);

-- RLS
alter table app_users enable row level security;
alter table families enable row level security;
alter table family_members enable row level security;
alter table caregiver_profiles enable row level security;
alter table children enable row level security;
alter table memory_chunks enable row level security;
alter table conversation_sessions enable row level security;
alter table conversation_messages enable row level security;
alter table activity_logs enable row level security;
alter table timeline_events enable row level security;
alter table tasks enable row level security;
alter table routine_metrics enable row level security;
alter table daily_child_metrics enable row level security;
alter table knowledge_items enable row level security;
alter table inferences enable row level security;
alter table message_feedback enable row level security;
alter table share_links enable row level security;
alter table loading_metrics enable row level security;

-- app_users
create policy app_users_select on app_users
  for select using (auth_user_id = auth.uid());
create policy app_users_insert on app_users
  for insert with check (auth_user_id = auth.uid());
create policy app_users_update on app_users
  for update using (auth_user_id = auth.uid());

-- families
create policy families_select on families
  for select using (
    exists (select 1 from family_members fm where fm.family_id = families.id and fm.user_id = auth.uid())
  );
create policy families_insert on families
  for insert with check (auth.uid() is not null);
create policy families_update on families
  for update using (
    exists (select 1 from family_members fm where fm.family_id = families.id and fm.user_id = auth.uid())
  );
create policy families_delete on families
  for delete using (false);

-- family_members
create policy family_members_select on family_members
  for select using (
    exists (select 1 from family_members fm where fm.family_id = family_members.family_id and fm.user_id = auth.uid())
  );
create policy family_members_insert on family_members
  for insert with check (user_id = auth.uid());
create policy family_members_update on family_members
  for update using (user_id = auth.uid());
create policy family_members_delete on family_members
  for delete using (user_id = auth.uid());

-- caregiver_profiles
create policy caregiver_profiles_select on caregiver_profiles
  for select using (user_id = auth.uid());
create policy caregiver_profiles_insert on caregiver_profiles
  for insert with check (user_id = auth.uid());
create policy caregiver_profiles_update on caregiver_profiles
  for update using (user_id = auth.uid());

-- children
create policy children_select on children
  for select using (
    exists (select 1 from family_members fm where fm.family_id = children.family_id and fm.user_id = auth.uid())
  );
create policy children_insert on children
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = children.family_id and fm.user_id = auth.uid())
  );
create policy children_update on children
  for update using (
    exists (select 1 from family_members fm where fm.family_id = children.family_id and fm.user_id = auth.uid())
  );
create policy children_delete on children
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = children.family_id and fm.user_id = auth.uid())
  );

-- memory_chunks
create policy memory_chunks_select on memory_chunks
  for select using (
    exists (select 1 from family_members fm where fm.family_id = memory_chunks.family_id and fm.user_id = auth.uid())
  );
create policy memory_chunks_insert on memory_chunks
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = memory_chunks.family_id and fm.user_id = auth.uid())
  );
create policy memory_chunks_update on memory_chunks
  for update using (
    exists (select 1 from family_members fm where fm.family_id = memory_chunks.family_id and fm.user_id = auth.uid())
  );
create policy memory_chunks_delete on memory_chunks
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = memory_chunks.family_id and fm.user_id = auth.uid())
  );

-- conversation_sessions
create policy conversation_sessions_select on conversation_sessions
  for select using (
    exists (select 1 from family_members fm where fm.family_id = conversation_sessions.family_id and fm.user_id = auth.uid())
  );
create policy conversation_sessions_insert on conversation_sessions
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = conversation_sessions.family_id and fm.user_id = auth.uid())
  );
create policy conversation_sessions_update on conversation_sessions
  for update using (
    exists (select 1 from family_members fm where fm.family_id = conversation_sessions.family_id and fm.user_id = auth.uid())
  );
create policy conversation_sessions_delete on conversation_sessions
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = conversation_sessions.family_id and fm.user_id = auth.uid())
  );

-- conversation_messages (join sessions -> family_members)
create policy conversation_messages_select on conversation_messages
  for select using (
    exists (
      select 1
      from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = conversation_messages.session_id and fm.user_id = auth.uid()
    )
  );
create policy conversation_messages_insert on conversation_messages
  for insert with check (
    exists (
      select 1
      from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = conversation_messages.session_id and fm.user_id = auth.uid()
    )
  );
create policy conversation_messages_update on conversation_messages
  for update using (
    exists (
      select 1
      from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = conversation_messages.session_id and fm.user_id = auth.uid()
    )
  );
create policy conversation_messages_delete on conversation_messages
  for delete using (
    exists (
      select 1
      from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = conversation_messages.session_id and fm.user_id = auth.uid()
    )
  );

-- activity_logs
create policy activity_logs_select on activity_logs
  for select using (
    exists (select 1 from family_members fm where fm.family_id = activity_logs.family_id and fm.user_id = auth.uid())
  );
create policy activity_logs_insert on activity_logs
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = activity_logs.family_id and fm.user_id = auth.uid())
  );
create policy activity_logs_update on activity_logs
  for update using (
    exists (select 1 from family_members fm where fm.family_id = activity_logs.family_id and fm.user_id = auth.uid())
  );
create policy activity_logs_delete on activity_logs
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = activity_logs.family_id and fm.user_id = auth.uid())
  );

-- timeline_events
create policy timeline_events_select on timeline_events
  for select using (
    exists (select 1 from family_members fm where fm.family_id = timeline_events.family_id and fm.user_id = auth.uid())
  );
create policy timeline_events_insert on timeline_events
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = timeline_events.family_id and fm.user_id = auth.uid())
  );
create policy timeline_events_update on timeline_events
  for update using (
    exists (select 1 from family_members fm where fm.family_id = timeline_events.family_id and fm.user_id = auth.uid())
  );
create policy timeline_events_delete on timeline_events
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = timeline_events.family_id and fm.user_id = auth.uid())
  );

-- tasks
create policy tasks_select on tasks
  for select using (
    exists (select 1 from family_members fm where fm.family_id = tasks.family_id and fm.user_id = auth.uid())
  );
create policy tasks_insert on tasks
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = tasks.family_id and fm.user_id = auth.uid())
  );
create policy tasks_update on tasks
  for update using (
    exists (select 1 from family_members fm where fm.family_id = tasks.family_id and fm.user_id = auth.uid())
  );
create policy tasks_delete on tasks
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = tasks.family_id and fm.user_id = auth.uid())
  );

-- routine_metrics (child-scoped)
create policy routine_metrics_select on routine_metrics
  for select using (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = routine_metrics.child_id and fm.user_id = auth.uid()
    )
  );
create policy routine_metrics_insert on routine_metrics
  for insert with check (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = routine_metrics.child_id and fm.user_id = auth.uid()
    )
  );
create policy routine_metrics_update on routine_metrics
  for update using (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = routine_metrics.child_id and fm.user_id = auth.uid()
    )
  );
create policy routine_metrics_delete on routine_metrics
  for delete using (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = routine_metrics.child_id and fm.user_id = auth.uid()
    )
  );

-- daily_child_metrics
create policy daily_child_metrics_select on daily_child_metrics
  for select using (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = daily_child_metrics.child_id and fm.user_id = auth.uid()
    )
  );
create policy daily_child_metrics_insert on daily_child_metrics
  for insert with check (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = daily_child_metrics.child_id and fm.user_id = auth.uid()
    )
  );
create policy daily_child_metrics_update on daily_child_metrics
  for update using (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = daily_child_metrics.child_id and fm.user_id = auth.uid()
    )
  );
create policy daily_child_metrics_delete on daily_child_metrics
  for delete using (
    exists (
      select 1 from children c join family_members fm on fm.family_id = c.family_id
      where c.id = daily_child_metrics.child_id and fm.user_id = auth.uid()
    )
  );

-- knowledge_items
create policy knowledge_items_select on knowledge_items
  for select using (
    exists (select 1 from family_members fm where fm.family_id = knowledge_items.family_id and fm.user_id = auth.uid())
  );
create policy knowledge_items_insert on knowledge_items
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = knowledge_items.family_id and fm.user_id = auth.uid())
  );
create policy knowledge_items_update on knowledge_items
  for update using (
    exists (select 1 from family_members fm where fm.family_id = knowledge_items.family_id and fm.user_id = auth.uid())
  );
create policy knowledge_items_delete on knowledge_items
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = knowledge_items.family_id and fm.user_id = auth.uid())
  );

-- inferences
create policy inferences_select on inferences
  for select using (
    exists (select 1 from family_members fm where fm.family_id = inferences.family_id and fm.user_id = auth.uid())
  );
create policy inferences_insert on inferences
  for insert with check (
    exists (select 1 from family_members fm where fm.family_id = inferences.family_id and fm.user_id = auth.uid())
  );
create policy inferences_update on inferences
  for update using (
    exists (select 1 from family_members fm where fm.family_id = inferences.family_id and fm.user_id = auth.uid())
  );
create policy inferences_delete on inferences
  for delete using (
    exists (select 1 from family_members fm where fm.family_id = inferences.family_id and fm.user_id = auth.uid())
  );

-- message_feedback (join conversation_sessions)
create policy message_feedback_select on message_feedback
  for select using (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = message_feedback.conversation_id and fm.user_id = auth.uid()
    )
  );
create policy message_feedback_insert on message_feedback
  for insert with check (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = message_feedback.conversation_id and fm.user_id = auth.uid()
    )
  );
create policy message_feedback_update on message_feedback
  for update using (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = message_feedback.conversation_id and fm.user_id = auth.uid()
    )
  );
create policy message_feedback_delete on message_feedback
  for delete using (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = message_feedback.conversation_id and fm.user_id = auth.uid()
    )
  );

-- share_links (public share should be handled via service role in BFF)
create policy share_links_select on share_links
  for select using (auth.uid() is not null);
create policy share_links_insert on share_links
  for insert with check (auth.uid() is not null);
create policy share_links_update on share_links
  for update using (auth.uid() is not null);
create policy share_links_delete on share_links
  for delete using (auth.uid() is not null);

-- loading_metrics (join conversation_sessions)
create policy loading_metrics_select on loading_metrics
  for select using (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = loading_metrics.session_id and fm.user_id = auth.uid()
    )
  );
create policy loading_metrics_insert on loading_metrics
  for insert with check (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = loading_metrics.session_id and fm.user_id = auth.uid()
    )
  );
create policy loading_metrics_update on loading_metrics
  for update using (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = loading_metrics.session_id and fm.user_id = auth.uid()
    )
  );
create policy loading_metrics_delete on loading_metrics
  for delete using (
    exists (
      select 1 from conversation_sessions s
      join family_members fm on fm.family_id = s.family_id
      where s.id = loading_metrics.session_id and fm.user_id = auth.uid()
    )
  );
